[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = "Project"
authors = ["AlutkaG"]
license = "mit"

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
